[package]
name = "windivert-sys"
version = "0.1.1"
authors = ["ray851107 <ray851107@gmail.com>", "JohnDoneth <doneth7@gmail.com>"]

[dependencies]
winapi = { version = "0.3.4", features = ["basetsd", "ntdef", "minwindef", "minwinbase", "ntdef"] }